### ISSUE TITLE
Brightness control working on the T14s?

### ISSUE THREAD

**Issue by carterprince** [anonymix007/x1e-firmware#3]
I installed the firmware on my machine (from a copy of my own Windows partition) for the T14s. I'm using the Ubuntu Concept image and things are mostly working (with notable exceptions like brightness control, audio output to speakers, and some USB issues).

But I want to ask -- was anyone able to get brightness control working?

I noticed some of the firmware in this repo have different contents from the firmware from my Windows install, notably `LENOVO/21N1/qcdxkmsuc8380.mbn` which seems to contain the firmware for screen brightness control.

Do you think switching to this firmware would fix it? My guess is probably not, but I thought it's still worth asking.

**Comment by anonymix007** [comment]
No, different firmware wouldn't fix anything here. But [this](https://git.codelinaro.org/abel.vesa/linux/-/commit/75fdd3465ec4bb67b169b471427818b69cf09887) might. Haven't tried by myself yet though.

**Comment by jglathe** [comment]
wow, thanks for the link. Will try

**Comment by jglathe** [comment]
I got it working on HP Omnibook X14, too. Same on T14s (IPS Panel). This is the [T14s variant](https://github.com/jglathe/linux_ms_dev_kit/commit/e2de95a7b5b6bc6b95d44948370dccae327d7ec6) with a brightness curve that makes usage a little easier (Levels 0..100).
